const PRODUCTS_DB = [
  {
    "id": 1,
    "code": "GSA001",
    "name": "ممسحة مسطحة شينيل",
    "name_en": "Chenille  Flat Mop",
    "desc": "ممسحة مسطحة 40 سم، رأس ممسحة شينيل قابل للاستبدال، مقبض معدني قابل للتطويل من 73 إلى 130 سم بقطر 19-22 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image181.jpeg",
    "price": 71,
    "oldPrice": 96,
    "badge": "",
    "stars": 4.6,
    "reviews": 63,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 2,
    "code": "GSR-A001",
    "name": "رأس ممسحة شينيل بديل",
    "name_en": "Chenille  Mop Refill",
    "desc": "الوزن 125 جم، مناسب للموديل GSA001، المقاس: 43.5×13 سم.",
    "cat": "قطع غيار",
    "img": "product_images/image10.png",
    "price": 30,
    "oldPrice": 41,
    "badge": "",
    "stars": 4.7,
    "reviews": 76,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 3,
    "code": "KA2210",
    "name": "ممسحة مسطحة",
    "name_en": "Flat mop",
    "desc": "ممسحة مسطحة مقاس 40×10 سم، رأس ممسحة شينيل بديل مقاس 43×13 سم، مقبض معدني قابل للتطويل من 70 إلى 120 سم.",
    "cat": "قطع غيار",
    "img": "product_images/image85.png",
    "price": 63,
    "oldPrice": 85,
    "badge": "",
    "stars": 4.8,
    "reviews": 89,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 4,
    "code": "KR2204",
    "name": "رأس ممسحة بديل من الألياف الدقيقة",
    "name_en": "Microfiber mop refill",
    "desc": "رأس بديل للموديل KA2210، المقاس: 43×13 سم، التغليف: بطاقة ورقية + كيس شفاف (OPP).",
    "cat": "قطع غيار",
    "img": "product_images/image84.png",
    "price": 25,
    "oldPrice": 34,
    "badge": "",
    "stars": 4.9,
    "reviews": 102,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 5,
    "code": "KA2525",
    "name": "ممسحة من الألياف الدقيقة",
    "name_en": "Microfiber Mop",
    "desc": "ممسحة مسطحة 40 سم، رأس ممسحة من الألياف الدقيقة مقاس 44×14 سم، مقبض معدني قابل للتطويل من 73 إلى 125 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image160.jpeg",
    "price": 73,
    "oldPrice": 99,
    "badge": "",
    "stars": 4.5,
    "reviews": 115,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 6,
    "code": "R-KA2525",
    "name": "رأس ممسحة بديل",
    "name_en": "Mop refill",
    "desc": "المقاس: 44×14 سم؛ رأس ممسحة بديل من الألياف الدقيقة.",
    "cat": "قطع غيار",
    "img": "product_images/image173.jpeg",
    "price": 30,
    "oldPrice": 40,
    "badge": "",
    "stars": 4.6,
    "reviews": 128,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 7,
    "code": "KA2519",
    "name": "ممسحة من الألياف الدقيقة",
    "name_en": "Microfiber Mop",
    "desc": "ممسحة مسطحة 52 سم، رأس ممسحة من الألياف الدقيقة مقاس 54.5×15 سم، مقبض معدني قابل للتطويل من 75 إلى 130 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image113.jpeg",
    "price": 118,
    "oldPrice": 159,
    "badge": "",
    "stars": 4.7,
    "reviews": 141,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 8,
    "code": "KA2208",
    "name": "ممسحة مسطحة",
    "name_en": "Flat mop",
    "desc": "ممسحة مسطحة 38 سم، رأس ممسحة من الألياف الدقيقة مقاس 41.5×12.5 سم، مقبض معدني قابل للتطويل بقطر 19-22 مم من 70 إلى 120 سم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image26.png",
    "price": 61,
    "oldPrice": 82,
    "badge": "",
    "stars": 4.8,
    "reviews": 154,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 9,
    "code": "KR2203",
    "name": "رأس ممسحة بديل",
    "name_en": "Mop refill",
    "desc": "رأس بديل للموديل KA2208، المقاس: 41.5×12.5 سم، التغليف: بطاقة ورقية + كيس شفاف.",
    "cat": "قطع غيار",
    "img": "product_images/image27.png",
    "price": 22,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.9,
    "reviews": 167,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 10,
    "code": "K19008",
    "name": "ممسحة مسطحة من الألياف الدقيقة",
    "name_en": "Microfiber Flat Mop",
    "desc": "طقم ممسحة مسطحة مقاس 41×10.5 سم، رأس بديل من الألياف الدقيقة، مقبض معدني قابل للتطويل من 75 إلى 130 سم بقطر 22/25 مم.",
    "cat": "قطع غيار",
    "img": "product_images/image69.png",
    "price": 92,
    "oldPrice": 125,
    "badge": "",
    "stars": 4.5,
    "reviews": 180,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 11,
    "code": "K19008-R",
    "name": "رأس ممسحة بديل من الألياف الدقيقة",
    "name_en": "Microfiber Mop refill",
    "desc": "المقاس: 45×14 سم، رأس ممسحة بديل من الألياف الدقيقة موديل K190008، بتصميم الجيب.",
    "cat": "قطع غيار",
    "img": "product_images/image31.jpeg",
    "price": 31,
    "oldPrice": 42,
    "badge": "",
    "stars": 4.6,
    "reviews": 193,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 12,
    "code": "KA2312",
    "name": "ممسحة مسطحة من الألياف الدقيقة",
    "name_en": "Microfiber Flat Mop",
    "desc": "ممسحة مسطحة من الألياف الدقيقة، مقاس الرأس: 37×11 سم، رأس بديل واحد بنظام الفيلكرو، مقبض معدني قابل للتطويل من 75 إلى 130 سم بقطر 21.5/25 مم، تغليف ببطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image96.jpeg",
    "price": 82,
    "oldPrice": 111,
    "badge": "",
    "stars": 4.7,
    "reviews": 206,
    "color": "white&blue",
    "inStock": true
  },
  {
    "id": 13,
    "code": "R-KA2312",
    "name": "رأس ممسحة بديل",
    "name_en": "MOP REFILL",
    "desc": "رأس بديل من الألياف الدقيقة للممسحة المسطحة KA2312، بنظام الفيلكرو من الخلف، المقاس: 38×13 سم، التغليف: بطاقة ورقية + كيس بلاستيكي.",
    "cat": "قطع غيار",
    "img": "product_images/image97.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.8,
    "reviews": 219,
    "color": "white&blue",
    "inStock": true
  },
  {
    "id": 14,
    "code": "KA2315",
    "name": "ممسحة مسطحة من الألياف الدقيقة",
    "name_en": "Microfiber Flat Mop",
    "desc": "ممسحة مسطحة من الألياف الدقيقة، مقاس الرأس: 47×13.2 سم، رأس بديل واحد من الألياف الدقيقة، مقبض معدني قابل للتطويل من 75 إلى 130 سم بقطر 21.5/25 مم، تغليف ببطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image100.jpeg",
    "price": 104,
    "oldPrice": 140,
    "badge": "",
    "stars": 4.9,
    "reviews": 232,
    "color": "white&blue",
    "inStock": true
  },
  {
    "id": 15,
    "code": "R-KA2315",
    "name": "رأس ممسحة بديل من الألياف الدقيقة 48 سم",
    "name_en": "48CM Microfiber mop refill",
    "desc": "رأس ممسحة بديل من الألياف الدقيقة، المقاس: 48×15.5 سم، طول الخيوط الحلقية 3 سم، بتصميم الجيب، التغليف: بطاقة ورقية + كيس شفاف، 24 قطعة/كرتون.",
    "cat": "قطع غيار",
    "img": "product_images/image98.jpeg",
    "price": 38,
    "oldPrice": 51,
    "badge": "",
    "stars": 4.5,
    "reviews": 245,
    "color": "white",
    "inStock": true
  },
  {
    "id": 16,
    "code": "KA2526",
    "name": "ممسحة قطنية",
    "name_en": "Cotton Mop",
    "desc": "ممسحة مسطحة 40 سم، رأس ممسحة قطنية بديلة مقاس 43×13 سم، مقبض معدني قابل للتطويل من 73 إلى 125 سم، رأس دوّار بزاوية 360 درجة.",
    "cat": "مماسح قطنية",
    "img": "product_images/image161.jpeg",
    "price": 80,
    "oldPrice": 108,
    "badge": "",
    "stars": 4.6,
    "reviews": 258,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 17,
    "code": "R-KA2526",
    "name": "رأس ممسحة بديل من القطن المخلوط",
    "name_en": "mix cotton Mop refill",
    "desc": "المقاس: 43×13 سم؛ طول الخيوط 3.5 سم، رأس ممسحة بديل من القطن المخلوط.",
    "cat": "مماسح قطنية",
    "img": "product_images/image172.jpeg",
    "price": 36,
    "oldPrice": 48,
    "badge": "",
    "stars": 4.7,
    "reviews": 271,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 18,
    "code": "KA2523",
    "name": "ممسحة قطنية 52 سم",
    "name_en": "Cotton Mop 52cm",
    "desc": "ممسحة مسطحة 52 سم، رأس ممسحة قطنية بديلة مقاس 54×15 سم، مقبض معدني قابل للتطويل من 74 إلى 130 سم، رأس دوّار بزاوية 360 درجة.",
    "cat": "مماسح قطنية",
    "img": "product_images/image142.jpeg",
    "price": 115,
    "oldPrice": 155,
    "badge": "",
    "stars": 4.8,
    "reviews": 284,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 19,
    "code": "GSA011",
    "name": "ممسحة قطنية احترافية",
    "name_en": "Professional Cotton Mop",
    "desc": "ممسحة مسطحة 60 سم، رأس ممسحة بديل من القطن المخلوط، مقبض معدني طول 135 سم (يشمل المشبك ومقبض اليد).",
    "cat": "مماسح قطنية",
    "img": "product_images/image29.png",
    "price": 118,
    "oldPrice": 159,
    "badge": "",
    "stars": 4.9,
    "reviews": 297,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 20,
    "code": "GSR-A011",
    "name": "رأس ممسحة قطنية بديل",
    "name_en": "Cotton Mop refill",
    "desc": "رأس ممسحة بديل من القطن المخلوط للموديل GSA011؛ المقاس: 60×16.5 سم.",
    "cat": "مماسح قطنية",
    "img": "product_images/image86.png",
    "price": 48,
    "oldPrice": 65,
    "badge": "",
    "stars": 4.5,
    "reviews": 60,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 21,
    "code": "KA2524",
    "name": "ممسحة مسطحة من الألياف الدقيقة",
    "name_en": "Microfiber Flat Mop",
    "desc": "ممسحة مسطحة من الألياف الدقيقة، مقاس الرأس: 54×12 سم، رأس بديل واحد بنظام الفيلكرو، مقبض معدني قابل للتطويل من 74 إلى 130 سم بقطر 21.5/25 مم، تغليف ببطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image178.jpeg",
    "price": 107,
    "oldPrice": 144,
    "badge": "",
    "stars": 4.6,
    "reviews": 73,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 22,
    "code": "R-KA2524",
    "name": "رأس ممسحة بديل",
    "name_en": "MOP REFILL",
    "desc": "رأس بديل من الألياف الدقيقة للممسحة المسطحة KA2524، بنظام الفيلكرو من الخلف، المقاس: 57×14.5 سم، التغليف: بطاقة ورقية + كيس بلاستيكي.",
    "cat": "قطع غيار",
    "img": "product_images/image149.jpeg",
    "price": 34,
    "oldPrice": 45,
    "badge": "",
    "stars": 4.7,
    "reviews": 86,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 23,
    "code": "GSA010",
    "name": "ممسحة ملتوية (تويست)",
    "name_en": "Twist Mop",
    "desc": "رأس ممسحة من الألياف الدقيقة، مقبض معدني طول 120 سم، بخاصية القفل الذاتي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image42.png",
    "price": 58,
    "oldPrice": 78,
    "badge": "",
    "stars": 4.8,
    "reviews": 99,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 24,
    "code": "K19022",
    "name": "ممسحة مائية قطنية",
    "name_en": "Cotton Water Mop",
    "desc": "رأس قطن مخلوط وزن 200 جم، مقبض معدني طول 130 سم، قطر 21.5 مم مع رأس بربطة حلزونية إيطالية.",
    "cat": "مماسح قطنية",
    "img": "product_images/image203.jpeg",
    "price": 37,
    "oldPrice": 50,
    "badge": "",
    "stars": 4.9,
    "reviews": 112,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 25,
    "code": "K19023",
    "name": "ممسحة مائية من الألياف الدقيقة",
    "name_en": "Microfiber Water Mop",
    "desc": "رأس من الألياف الدقيقة وزن 160 جم، مقبض معدني طول 130 سم، قطر 21.5 مم مع رأس بربطة حلزونية إيطالية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image204.jpeg",
    "price": 44,
    "oldPrice": 59,
    "badge": "",
    "stars": 4.5,
    "reviews": 125,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 26,
    "code": "K19024",
    "name": "ممسحة ملتوية (تويست)",
    "name_en": "Twist Mop",
    "desc": "رأس قطن مخلوط وزن 300 جم، مقبض معدني طول 130 سم، بخاصية القفل الذاتي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image205.jpeg",
    "price": 72,
    "oldPrice": 97,
    "badge": "",
    "stars": 4.6,
    "reviews": 138,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 27,
    "code": "K19025",
    "name": "ممسحة ملتوية (تويست)",
    "name_en": "Twist Mop",
    "desc": "رأس ممسحة ملتوية من الألياف الدقيقة، مقبض معدني طول 130 سم، بخاصية القفل الذاتي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image206.jpeg",
    "price": 72,
    "oldPrice": 97,
    "badge": "",
    "stars": 4.7,
    "reviews": 151,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 28,
    "code": "GSA031",
    "name": "ممسحة قطنية",
    "name_en": "Cotton Mop",
    "desc": "رأس ممسحة من القطن المخلوط وزن 450 جم، طول الخيوط 36 سم، مقبض معدني طول 130 سم بقطر 22 مم، حامل ممسحة بلاستيكي، التغليف: كيس شفاف + بطاقة ورقية.",
    "cat": "مماسح قطنية",
    "img": "product_images/image202.jpeg",
    "price": 93,
    "oldPrice": 125,
    "badge": "",
    "stars": 4.8,
    "reviews": 164,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 29,
    "code": "GSA004",
    "name": "ممسحة PVA السحرية",
    "name_en": "PVA Magic Mop",
    "desc": "رأس إسفنج PVA مقاس 27 سم قابل للاستبدال، مقبض من الفولاذ المقاوم للصدأ قابل للتطويل من 76 إلى 107 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image183.jpeg",
    "price": 82,
    "oldPrice": 111,
    "badge": "",
    "stars": 4.9,
    "reviews": 177,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 30,
    "code": "GSA005",
    "name": "ممسحة PVA السحرية",
    "name_en": "PVA Magic Mop",
    "desc": "رأس إسفنج PVA مقاس 27 سم قابل للاستبدال، مقبض من الفولاذ المقاوم للصدأ قابل للتطويل من 70 إلى 106 سم، بقطر 2.2/2.5 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image184.jpeg",
    "price": 82,
    "oldPrice": 111,
    "badge": "",
    "stars": 4.5,
    "reviews": 190,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 31,
    "code": "GSA034",
    "name": "ممسحة PVA السحرية",
    "name_en": "PVA Magic Mop",
    "desc": "طقم ممسحة PVA ناعمة مقاس 33 سم، مقبض فولاذي مقاوم للصدأ متين قابل للتطويل من 88 إلى 115 سم، بلونين أزرق ورمادي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image182.jpeg",
    "price": 117,
    "oldPrice": 157,
    "badge": "",
    "stars": 4.6,
    "reviews": 203,
    "color": "Blue & Grey",
    "inStock": true
  },
  {
    "id": 32,
    "code": "GSA032",
    "name": "ممسحة رذاذ",
    "name_en": "Spray Mop",
    "desc": "ممسحة رذاذ، مقبض معدني طول 120 سم، سعة الخزان: 280 مل، مقاس لوح الممسحة: 36×11 سم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image109.jpeg",
    "price": 121,
    "oldPrice": 163,
    "badge": "",
    "stars": 4.7,
    "reviews": 216,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 33,
    "code": "GSR-A014",
    "name": "رأس بديل لممسحة الرذاذ",
    "name_en": "Spray Mop refill",
    "desc": "رأس بديل من الألياف الدقيقة مقاس 39×12 سم لممسحة الرذاذ GSA014.",
    "cat": "قطع غيار",
    "img": "product_images/image13.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.8,
    "reviews": 229,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 34,
    "code": "KA2202",
    "name": "ممسحة رذاذ",
    "name_en": "SPRAY MOP",
    "desc": "ممسحة رذاذ مقاس 38×10 سم، رأس بديل من الألياف الدقيقة مقاس 41×13 سم، زجاجة PET قابلة للفك بسعة 500 مل، الطول الكلي للممسحة 118 سم بقطر 22 مم، مقبض ألمنيوم بقبضة ناعمة، تغليف ببطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image24.png",
    "price": 172,
    "oldPrice": 232,
    "badge": "",
    "stars": 4.9,
    "reviews": 242,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 35,
    "code": "KR2201",
    "name": "رأس بديل لممسحة الرذاذ",
    "name_en": "SPRAY MOP REFILL",
    "desc": "رأس بديل من الألياف الدقيقة لممسحات الرذاذ KA2202/KA2204/KA2206، بنظام الفيلكرو من الخلف، المقاس: 41×13 سم، التغليف: بطاقة ورقية + كيس بلاستيكي.",
    "cat": "قطع غيار",
    "img": "product_images/image25.png",
    "price": 24,
    "oldPrice": 33,
    "badge": "",
    "stars": 4.5,
    "reviews": 255,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 36,
    "code": "GSB002",
    "name": "منظف نوافذ 8 إنش",
    "name_en": "Window Cleaner 8\"",
    "desc": "رأس تنظيف مقاس 8 إنش، وصلة حلزونية، مقبض ألمنيوم قابل للتطويل من 45 إلى 73 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image91.png",
    "price": 41,
    "oldPrice": 56,
    "badge": "",
    "stars": 4.6,
    "reviews": 268,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 37,
    "code": "GSB003",
    "name": "منظف نوافذ 10 إنش",
    "name_en": "Window Cleaner 10\"",
    "desc": "رأس تنظيف مقاس 10 إنش، وصلة حلزونية، مقبض ألمنيوم قابل للتطويل من 45 إلى 73 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image70.png",
    "price": 46,
    "oldPrice": 62,
    "badge": "",
    "stars": 4.7,
    "reviews": 281,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 38,
    "code": "K19009",
    "name": "منظف نوافذ",
    "name_en": "Window Cleaner",
    "desc": "رأس تنظيف 29 سم + رأس من الألياف الدقيقة 27.5 سم، مقبض معدني قابل للتطويل من 75 إلى 130 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image76.png",
    "price": 72,
    "oldPrice": 97,
    "badge": "",
    "stars": 4.8,
    "reviews": 294,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 39,
    "code": "KB2201",
    "name": "منظف نوافذ 8 إنش",
    "name_en": "Window Cleaner 8\"",
    "desc": "رأس تنظيف 8 إنش، دوّار بزاوية 360 درجة، مقبض ألمنيوم قابل للتطويل من 53 إلى 80.5 سم (شاملاً الجزء البلاستيكي) بقطر 19-22 مم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image76.png",
    "price": 71,
    "oldPrice": 96,
    "badge": "",
    "stars": 4.9,
    "reviews": 57,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 40,
    "code": "KB2202",
    "name": "منظف نوافذ 10 إنش",
    "name_en": "Window Cleaner 10\"",
    "desc": "رأس تنظيف 10 إنش، دوّار بزاوية 360 درجة، مقبض ألمنيوم قابل للتطويل من 78 إلى 130 سم (شاملاً الجزء البلاستيكي) بقطر 19-22 مم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image77.png",
    "price": 91,
    "oldPrice": 123,
    "badge": "",
    "stars": 4.5,
    "reviews": 70,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 41,
    "code": "KB2203",
    "name": "منظف نوافذ 12 إنش",
    "name_en": "Window Cleaner 12\"",
    "desc": "رأس تنظيف 12 إنش، دوّار بزاوية 360 درجة، مقبض ألمنيوم قابل للتطويل من 110 إلى 180 سم (شاملاً الجزء البلاستيكي) بقطر 21.7-25 مم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image78.png",
    "price": 137,
    "oldPrice": 185,
    "badge": "",
    "stars": 4.6,
    "reviews": 83,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 42,
    "code": "GSB008",
    "name": "منظف نوافذ",
    "name_en": "Window Cleaner",
    "desc": "مسّاحة (سكرابر) من مادة TPR مقاس 20 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image2.jpeg",
    "price": 13,
    "oldPrice": 18,
    "badge": "",
    "stars": 4.7,
    "reviews": 96,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 43,
    "code": "GSB010",
    "name": "طقم منظف نوافذ",
    "name_en": "Window Cleaner set",
    "desc": "رأس تنظيف 30 سم + رأس من الألياف الدقيقة 32 سم، رأسان بديلان من الألياف الدقيقة، مقبض معدني قابل للتطويل من 85 إلى 150 سم بقطر 18/22/25 مم، التغليف: علبة بلاستيكية شفافة + بطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image18.png",
    "price": 101,
    "oldPrice": 137,
    "badge": "",
    "stars": 4.8,
    "reviews": 109,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 44,
    "code": "GSB012",
    "name": "منظف نوافذ 30 سم",
    "name_en": "30CM Window Cleaner",
    "desc": "رأس ألمنيوم مقاس 30 سم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image104.jpeg",
    "price": 19,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.9,
    "reviews": 122,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 45,
    "code": "KB2413",
    "name": "منظف نوافذ",
    "name_en": "Window Cleaner",
    "desc": "مسّاحة من مادة TPR مقاس 24 سم، بمقبض TPR ناعم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image107.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.5,
    "reviews": 135,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 46,
    "code": "K19019",
    "name": "مسّاحة (وايبر)",
    "name_en": "Wiper",
    "desc": "مسّاحة من مادة TPR مقاس 24 سم، بمقبض TPR ناعم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image72.png",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.6,
    "reviews": 148,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 47,
    "code": "GSB014",
    "name": "منظف نوافذ 35 سم",
    "name_en": "35CM Window Cleaner",
    "desc": "رأس ألمنيوم مقاس 35 سم، مقبض بلاستيكي، برأس ذو ربط حلزوني بالطراز الإيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image157.jpeg",
    "price": 25,
    "oldPrice": 33,
    "badge": "",
    "stars": 4.7,
    "reviews": 161,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 48,
    "code": "GSB015",
    "name": "منظف نوافذ 45 سم",
    "name_en": "45CM Window Cleaner",
    "desc": "رأس ألمنيوم مقاس 45 سم، مقبض بلاستيكي، برأس ذو ربط حلزوني بالطراز الإيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image158.jpeg",
    "price": 29,
    "oldPrice": 39,
    "badge": "",
    "stars": 4.8,
    "reviews": 174,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 49,
    "code": "GSB016",
    "name": "منظف نوافذ 25 سم",
    "name_en": "Window Cleaner 25cm",
    "desc": "رأس بلاستيكي أحمر مقاس 25 سم، رأس بديل رمادي من الألياف الدقيقة قابل للاستبدال، برأس ذو ربط حلزوني بالطراز الإيطالي.",
    "cat": "قطع غيار",
    "img": "product_images/image138.jpeg",
    "price": 25,
    "oldPrice": 33,
    "badge": "",
    "stars": 4.9,
    "reviews": 187,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 50,
    "code": "GSB018",
    "name": "منظف نوافذ 45 سم",
    "name_en": "Window Cleaner 45cm",
    "desc": "رأس بلاستيكي أحمر مقاس 45 سم، رأس بديل رمادي من الألياف الدقيقة قابل للاستبدال، برأس ذو ربط حلزوني بالطراز الإيطالي.",
    "cat": "قطع غيار",
    "img": "product_images/image139.jpeg",
    "price": 35,
    "oldPrice": 48,
    "badge": "",
    "stars": 4.5,
    "reviews": 200,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 51,
    "code": "GSE006-H",
    "name": "رأس منفضة PP",
    "name_en": "PP Duster head",
    "desc": "رأس منفضة من مادة PP، المقاس: 21×23.5 سم، برغي إيطالي، التغليف: حلقة بطاقة ورقية + كيس شفاف.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image179.jpeg",
    "price": 26,
    "oldPrice": 36,
    "badge": "",
    "stars": 4.6,
    "reviews": 213,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 52,
    "code": "GSM003",
    "name": "مقبض معدني قابل للتطويل 2.4 متر",
    "name_en": "2.4M telescopic metal handle",
    "desc": "مقبض معدني قابل للتطويل من 131 إلى 240 سم بقطر 19-22 مم، مع ملصق.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image175.jpeg",
    "price": 36,
    "oldPrice": 49,
    "badge": "",
    "stars": 4.7,
    "reviews": 226,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 53,
    "code": "GSM004",
    "name": "مقبض معدني قابل للتطويل 3 أمتار",
    "name_en": "3M telescopic metal handle",
    "desc": "مقبض معدني ثلاثي الأقسام قابل للتطويل من 120 إلى 300 سم بقطر 19-22-25 مم، مع ملصق.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image176.jpeg",
    "price": 56,
    "oldPrice": 76,
    "badge": "",
    "stars": 4.8,
    "reviews": 239,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 54,
    "code": "GSC003",
    "name": "جاروف وفرشاة",
    "name_en": "Dustpan & Brush",
    "desc": "جاروف قمامة مقاس 22 سم، طول الشعيرات 50 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image112.jpeg",
    "price": 23,
    "oldPrice": 31,
    "badge": "",
    "stars": 4.9,
    "reviews": 252,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 55,
    "code": "K19003",
    "name": "جاروف وفرشاة",
    "name_en": "Dustpan & Brush",
    "desc": "جاروف قمامة مقاس 24.5 سم، شعيرات PET طول 50 مم، يحمل علامة Kleaner التجارية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image67.png",
    "price": 33,
    "oldPrice": 45,
    "badge": "",
    "stars": 4.5,
    "reviews": 265,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 56,
    "code": "KC2002",
    "name": "جاروف وفرشاة",
    "name_en": "Dustpan & Brush",
    "desc": "جاروف قمامة مقاس 360×230×105 مم؛ طول الشعيرات 50 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image79.png",
    "price": 40,
    "oldPrice": 54,
    "badge": "",
    "stars": 4.6,
    "reviews": 278,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 57,
    "code": "KC2406",
    "name": "جاروف وفرشاة",
    "name_en": "Dustpan & Brush",
    "desc": "طقم جاروف قمامة بلاستيكي مقاس 33×24.5 سم؛ طول الشعيرات 5 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image115.jpeg",
    "price": 30,
    "oldPrice": 40,
    "badge": "",
    "stars": 4.7,
    "reviews": 291,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 58,
    "code": "GSC001",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "جاروف قمامة مقاس 25.5 سم، طول الشعيرات 80 مم، مقبض معدني 70 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image33.jpeg",
    "price": 49,
    "oldPrice": 66,
    "badge": "",
    "stars": 4.8,
    "reviews": 54,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 59,
    "code": "GSC004",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "طقم مكنسة وجاروف، المقاس: عرض 26 سم وعمق 25 سم، حافة الجاروف من مادة TPR، طول شعيرات المكنسة 75 مم، مقبض معدني 75 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image45.png",
    "price": 53,
    "oldPrice": 71,
    "badge": "",
    "stars": 4.9,
    "reviews": 67,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 60,
    "code": "GSC005",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "طقم مكنسة وجاروف، المقاس: عرض 26 سم، طول شعيرات المكنسة 75 مم، مقبض معدني 75 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image44.png",
    "price": 82,
    "oldPrice": 111,
    "badge": "",
    "stars": 4.5,
    "reviews": 80,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 61,
    "code": "K20004",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "طقم مكنسة وجاروف قابل للطي يحمل شعار Kleaner، المقاس: 24×26×9 سم، طول الشعيرات 90 مم، مقبض معدني 72 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image75.png",
    "price": 67,
    "oldPrice": 90,
    "badge": "",
    "stars": 4.6,
    "reviews": 93,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 62,
    "code": "GSC009",
    "name": "طقم جاروف ومكنسة",
    "name_en": "Dustpan & Broom Set",
    "desc": "طقم جاروف مقاوم للرياح، مقاس الجاروف 30×28×12 سم، مقاس المكنسة 21×22 سم بشعيرات طول 16 سم، مقبض معدني للمكنسة 80 سم بقبضة بلاستيكية، مقبض معدني للجاروف 75 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image46.png",
    "price": 139,
    "oldPrice": 187,
    "badge": "",
    "stars": 4.7,
    "reviews": 106,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 63,
    "code": "KC2511",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "طقم مكنسة وجاروف، المقاس: عرض 25×27 سم، طول شعيرات المكنسة 80 مم، مقبض معدني 80 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image162.jpeg",
    "price": 63,
    "oldPrice": 85,
    "badge": "",
    "stars": 4.8,
    "reviews": 119,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 64,
    "code": "KC2512",
    "name": "جاروف ومكنسة",
    "name_en": "Dustpan & Broom",
    "desc": "طقم مكنسة وجاروف، المقاس: عرض 24×27 سم، طول شعيرات المكنسة 80 مم، مقبض معدني 80 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image163.jpeg",
    "price": 74,
    "oldPrice": 100,
    "badge": "",
    "stars": 4.9,
    "reviews": 132,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 65,
    "code": "GSD001",
    "name": "طقم فرشاة مرحاض مع حامل",
    "name_en": "Toilet Brush & Caddy Set",
    "desc": "الطول 36.5 سم، طول الشعيرات 25 مم، مقاس المنتج: 11.5×11.5×36.5 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image9.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.5,
    "reviews": 145,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 66,
    "code": "GSD002",
    "name": "طقم فرشاة مرحاض مع حامل",
    "name_en": "Toilet Brush & Caddy Set",
    "desc": "الطول 37 سم، طول الشعيرات 25 مم، مقاس المنتج: 14.5×11.5×37 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image11.png",
    "price": 34,
    "oldPrice": 46,
    "badge": "",
    "stars": 4.6,
    "reviews": 158,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 67,
    "code": "K19014",
    "name": "طقم فرشاة مرحاض مع حامل",
    "name_en": "Toilet brush & Caddy Set",
    "desc": "الطول 36 سم، طول الشعيرات 29 مم، مقبض من مادة TPR، قاعدة بلاستيكية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image71.png",
    "price": 47,
    "oldPrice": 64,
    "badge": "",
    "stars": 4.7,
    "reviews": 171,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 68,
    "code": "KH2301",
    "name": "مكبس (بامب) مرحاض",
    "name_en": "PLUNGER",
    "desc": "الخامة: PP وTPE، مقبض بلاستيكي مكوّن من قسمين بطول إجمالي 43 سم، كأس شفط من TPE بقطر 15 سم، الوزن: 220 جم، مع ملصق.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image34.jpeg",
    "price": 31,
    "oldPrice": 42,
    "badge": "",
    "stars": 4.8,
    "reviews": 184,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 69,
    "code": "KD2309",
    "name": "طقم فرشاة مرحاض ومكبس",
    "name_en": "Toilet brush&Plunger set",
    "desc": "طقم فرشاة مرحاض ومكبس، الطول الإجمالي: 44 سم، طول الشعيرات 25 مم، كأس شفط TPE بقطر 15 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image35.jpeg",
    "price": 82,
    "oldPrice": 111,
    "badge": "",
    "stars": 4.9,
    "reviews": 197,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 70,
    "code": "GSD004",
    "name": "فرشاة مرحاض",
    "name_en": "Toilet Brush",
    "desc": "الطول 38.5 سم، طول الشعيرات 30 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image47.png",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.5,
    "reviews": 210,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 71,
    "code": "KD2410",
    "name": "فرشاة مرحاض",
    "name_en": "TOILET BRUSH",
    "desc": "الطول 44 سم، طول الشعيرات 25 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image108.jpeg",
    "price": 24,
    "oldPrice": 33,
    "badge": "",
    "stars": 4.6,
    "reviews": 223,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 72,
    "code": "KH2505",
    "name": "مكبس (بامب) مرحاض",
    "name_en": "Plunger",
    "desc": "الخامة: PP وTPE، طول المقبض البلاستيكي 41 سم، كأس شفط بقطر 15 سم، الوزن: 220 جم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image114.jpeg",
    "price": 30,
    "oldPrice": 41,
    "badge": "",
    "stars": 4.7,
    "reviews": 236,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 73,
    "code": "KH2507",
    "name": "مكبس (بامب) مرحاض",
    "name_en": "Plunger",
    "desc": "الخامة: PP وTPE، طول المقبض البلاستيكي 39.5 سم، كأس شفط بقطر 15 سم، الوزن: 160 جم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image168.jpeg",
    "price": 23,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.8,
    "reviews": 249,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 74,
    "code": "KH2508",
    "name": "مكبس (بامب) مرحاض",
    "name_en": "Plunger",
    "desc": "الخامة: PP وTPE، طول المقبض البلاستيكي 39.5 سم، كأس شفط بقطر 15 سم، الوزن: 160 جم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image167.jpeg",
    "price": 28,
    "oldPrice": 37,
    "badge": "",
    "stars": 4.9,
    "reviews": 262,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 75,
    "code": "KH2511",
    "name": "مكبس (بامب) مرحاض",
    "name_en": "Plunger",
    "desc": "الخامة: PP وTPE، طول المقبض البلاستيكي 42.5 سم، كأس شفط بقطر 14.5 سم، الوزن: 225 جم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image166.jpeg",
    "price": 35,
    "oldPrice": 47,
    "badge": "",
    "stars": 4.5,
    "reviews": 275,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 76,
    "code": "GSD007",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "المقاس: 156×68 مم، طول الشعيرات 28 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image48.png",
    "price": 14,
    "oldPrice": 19,
    "badge": "",
    "stars": 4.6,
    "reviews": 288,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 77,
    "code": "GSD009",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "المقاس: 145×65 مم، طول الشعيرات 20 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image49.png",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.7,
    "reviews": 51,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 78,
    "code": "GSD010",
    "name": "فرشاة زجاجات",
    "name_en": "Bottle Brush",
    "desc": "الطول 36 سم، طول الشعيرات 21 مم، مقبض من مادة PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image185.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.8,
    "reviews": 64,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 79,
    "code": "GSD012",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 27 سم، طول الشعيرات 27 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image50.png",
    "price": 14,
    "oldPrice": 19,
    "badge": "",
    "stars": 4.9,
    "reviews": 77,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 80,
    "code": "GSD015",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 26 سم، طول الشعيرات 24 مم، مقبض من مادة TPR.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image89.png",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.5,
    "reviews": 90,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 81,
    "code": "GSD025",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "المقاس: 15.7×6.7×4 سم، طول الشعيرات 27 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image209.jpeg",
    "price": 19,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.6,
    "reviews": 103,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 82,
    "code": "GSD026",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "المقاس: 15×6.5×9.5 سم، طول الشعيرات 28 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image210.jpeg",
    "price": 22,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.7,
    "reviews": 116,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 83,
    "code": "GSD027",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 28 سم، طول الشعيرات 28 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image211.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.8,
    "reviews": 129,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 84,
    "code": "GSD028",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 31 سم، طول الشعيرات 25 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image212.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.9,
    "reviews": 142,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 85,
    "code": "GSD029",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 30 سم، طول الشعيرات 28 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image213.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.5,
    "reviews": 155,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 86,
    "code": "GSD030",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 31 سم، طول الشعيرات 28 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image214.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.6,
    "reviews": 168,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 87,
    "code": "GSD031",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 31 سم، طول الشعيرات 28 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image215.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.7,
    "reviews": 181,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 88,
    "code": "GSD032",
    "name": "فرشاة",
    "name_en": "Brush",
    "desc": "الطول 30 سم، طول الشعيرات 28 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image216.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.8,
    "reviews": 194,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 89,
    "code": "GSD033",
    "name": "فرشاة متعددة الاستخدامات",
    "name_en": "Multi-Purpose Brush",
    "desc": "المقاس: 23×5.5×3.5 سم، طول الشعيرات 28 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image217.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.9,
    "reviews": 207,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 90,
    "code": "GSD034",
    "name": "فرشاة متعددة الاستخدامات",
    "name_en": "Multi-Purpose Brush",
    "desc": "الطول 25.5 سم، طول الشعيرات 25 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image218.jpeg",
    "price": 19,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.5,
    "reviews": 220,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 91,
    "code": "GSD035",
    "name": "فرشاة متعددة الاستخدامات",
    "name_en": "Multi-Purpose Brush",
    "desc": "الطول 28 سم، طول الشعيرات 25 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image219.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.6,
    "reviews": 233,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 92,
    "code": "GSD036",
    "name": "فرشاة أحذية",
    "name_en": "SHOE BRUSH",
    "desc": "الطول 25 سم، طول الشعيرات 25 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image220.jpeg",
    "price": 14,
    "oldPrice": 19,
    "badge": "",
    "stars": 4.7,
    "reviews": 246,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 93,
    "code": "GSD037",
    "name": "فرشاة استحمام",
    "name_en": "Bath Brush",
    "desc": "المقاس: 35×6.5×3 سم، طول الشعيرات 20 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image221.jpeg",
    "price": 15,
    "oldPrice": 21,
    "badge": "",
    "stars": 4.8,
    "reviews": 259,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 94,
    "code": "GSD038",
    "name": "فرشاة زجاجات",
    "name_en": "Bottle Brush",
    "desc": "الطول 39 سم، طول الشعيرات 25 مم، مقبض من مادة PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image222.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.9,
    "reviews": 272,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 95,
    "code": "GSD039",
    "name": "فرشاة نفض الغبار",
    "name_en": "Dusting brush",
    "desc": "الطول الإجمالي 30 سم، طول الشعيرات 50 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image223.jpeg",
    "price": 23,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.5,
    "reviews": 285,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 96,
    "code": "GSD040",
    "name": "فرشاة نفض الغبار",
    "name_en": "Dusting brush",
    "desc": "الطول الإجمالي 37 سم، طول الشعيرات 55 مم، مقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image224.jpeg",
    "price": 28,
    "oldPrice": 38,
    "badge": "",
    "stars": 4.6,
    "reviews": 298,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 97,
    "code": "GSD041",
    "name": "فرشاة متعددة الاستخدامات",
    "name_en": "Multi-Purpose Brush",
    "desc": "الطول الإجمالي 55 سم، طول الشعيرات 40 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image225.jpeg",
    "price": 25,
    "oldPrice": 33,
    "badge": "",
    "stars": 4.7,
    "reviews": 61,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 98,
    "code": "GSD042",
    "name": "فرشاة متعددة الاستخدامات",
    "name_en": "Multi-Purpose Brush",
    "desc": "الطول الإجمالي 46 سم، طول الشعيرات 38 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image226.jpeg",
    "price": 29,
    "oldPrice": 39,
    "badge": "",
    "stars": 4.8,
    "reviews": 74,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 99,
    "code": "GSD043",
    "name": "فرشاة مرحاض",
    "name_en": "Toilet brush",
    "desc": "الطول 39 سم، طول الشعيرات 29 مم، بلاستيك PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image227.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.9,
    "reviews": 87,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 100,
    "code": "GSD044",
    "name": "فرشاة مرحاض",
    "name_en": "Toilet brush",
    "desc": "الطول 54 سم، طول الشعيرات 25 مم، بلاستيك PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image228.jpeg",
    "price": 22,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.5,
    "reviews": 100,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 101,
    "code": "GSD045",
    "name": "طقم فرشاة مرحاض مع حامل",
    "name_en": "Toilet brush & Caddy Set",
    "desc": "الطول 40.5 سم، طول الشعيرات 25 مم، قاعدة ومقبض بلاستيكي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image229.jpeg",
    "price": 38,
    "oldPrice": 52,
    "badge": "",
    "stars": 4.6,
    "reviews": 113,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 102,
    "code": "GSB021",
    "name": "منظف نوافذ",
    "name_en": "Window Cleaner",
    "desc": "منظف نوافذ، مسّاحة TPR مقاس 8.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image230.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.7,
    "reviews": 126,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 103,
    "code": "GSB022",
    "name": "منظف نوافذ",
    "name_en": "Window Cleaner",
    "desc": "منظف نوافذ، مسّاحة TPR مقاس 10.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image231.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.8,
    "reviews": 139,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 104,
    "code": "GSD020",
    "name": "فرشاة زجاجات",
    "name_en": "bottle brush",
    "desc": "فرشاة زجاجات، الطول الإجمالي: 22.5 سم، مقبض من الفولاذ المقاوم للصدأ عيار 210، رأس اسفنجي شبكي PU، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image171.jpeg",
    "price": 15,
    "oldPrice": 21,
    "badge": "",
    "stars": 4.9,
    "reviews": 152,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 105,
    "code": "KD2104",
    "name": "فرشاة أطباق",
    "name_en": "Dish Brush",
    "desc": "فرشاة أطباق، الخامة: PP+TPR، المقاس: 5.5×8×10.5 سم، طول الشعيرات 3 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image80.png",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.5,
    "reviews": 165,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 106,
    "code": "KD2101",
    "name": "فرشاة أطباق مع خزان صابون",
    "name_en": "Soap Dispensing Dish Wand",
    "desc": "فرشاة أطباق مقاس 26×4×8.5 سم، طول الشعيرات 3 سم، مقبض ورأس بلاستيكي، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image19.png",
    "price": 26,
    "oldPrice": 36,
    "badge": "",
    "stars": 4.6,
    "reviews": 178,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 107,
    "code": "KD2102",
    "name": "فرشاة أطباق مع خزان صابون",
    "name_en": "Soap Dispensing Dish Wand",
    "desc": "فرشاة أطباق مقاس 26×4×8.5 سم، مقبض بلاستيكي ورأس إسفنجي، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image95.jpeg",
    "price": 27,
    "oldPrice": 36,
    "badge": "",
    "stars": 4.7,
    "reviews": 191,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 108,
    "code": "GSE001",
    "name": "منفضة PP",
    "name_en": "PP Duster",
    "desc": "رأس تنظيف قابل للانحناء بشعيرات PP مقاس 40 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image92.png",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.8,
    "reviews": 204,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 109,
    "code": "GSE002",
    "name": "منفضة من الألياف الدقيقة",
    "name_en": "Microfiber Duster",
    "desc": "رأس تنظيف قابل للانحناء من الألياف الدقيقة مقاس 35 سم، مقبض ألمنيوم قابل للتطويل من 80 إلى 120 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image88.png",
    "price": 66,
    "oldPrice": 89,
    "badge": "",
    "stars": 4.9,
    "reviews": 217,
    "color": "white",
    "inStock": true
  },
  {
    "id": 110,
    "code": "GSE003",
    "name": "منفضة من النسيج غير المنسوج 1+3",
    "name_en": "1+3                 non-woven duster",
    "desc": "طقم منفضة من النسيج غير المنسوج (وجه واحد) 1+3، يشمل مقبضاً بلاستيكياً واحداً مع 3 قطع بديلة، الطول الإجمالي للمنفضة 37 سم، مقاس رأس المنفضة 15×9 سم، وزن 14 جم × 3 قطع/طقم، تغليف كل طقم بكيس ملون، 12 طقم/كيس داخلي، 18 كيساً داخلياً/كرتون.",
    "cat": "قطع غيار",
    "img": "product_images/image146.jpeg",
    "price": 18,
    "oldPrice": 24,
    "badge": "",
    "stars": 4.5,
    "reviews": 230,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 111,
    "code": "GSG004",
    "name": "مناديل من الألياف الدقيقة 4 قطع",
    "name_en": "Microfiber Cloths 4pcs",
    "desc": "المقاس: 38×40 سم، الخامة: 80% بوليستر و20% بولي أميد، 4 قطع بثلاثة ألوان مختلطة لكل كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image51.png",
    "price": 34,
    "oldPrice": 45,
    "badge": "",
    "stars": 4.6,
    "reviews": 243,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 112,
    "code": "GSG005",
    "name": "مناديل من الألياف الدقيقة 6 قطع",
    "name_en": "Microfiber Cloths 6pcs",
    "desc": "المقاس: 38×40 سم، الخامة: 80% بوليستر و20% بولي أميد، 6 قطع بستة ألوان مختلطة لكل كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image101.jpeg",
    "price": 49,
    "oldPrice": 66,
    "badge": "",
    "stars": 4.7,
    "reviews": 256,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 113,
    "code": "GSG006",
    "name": "مناديل من الألياف الدقيقة 8 قطع",
    "name_en": "Microfiber Cloths 8pcs",
    "desc": "المقاس: 30×30 سم، الخامة: 80% بوليستر و20% بولي أميد، 8 قطع بأربعة ألوان مختلطة لكل كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image52.png",
    "price": 43,
    "oldPrice": 59,
    "badge": "",
    "stars": 4.8,
    "reviews": 269,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 114,
    "code": "GSG026",
    "name": "مناديل من الألياف الدقيقة 20 قطعة",
    "name_en": "Microfiber Cloths 20pcs",
    "desc": "قطع قماش من الألياف الدقيقة، المقاس: 20×30 سم، الوزن 200 جم/م²، الخامة: 80% بوليستر و20% بولي أميد، 10 قطع زرقاء و10 قطع رمادية لكل علبة، الإجمالي 20 قطعة، تغليف بعلبة ملونة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image145.jpeg",
    "price": 58,
    "oldPrice": 78,
    "badge": "",
    "stars": 4.9,
    "reviews": 282,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 115,
    "code": "GSG027",
    "name": "مناديل من الألياف الدقيقة",
    "name_en": "Microfiber Cloths",
    "desc": "قطع قماش من الألياف الدقيقة، 52 قطعة/لفة، مقاس كل قطعة: 22×22 سم، مقاس اللفة: قطر 13 سم × ارتفاع 22 سم، الوزن 200 جم/م²، الخامة: 85% بوليستر و15% بولي أميد، 12 لفة لكل كرتون، التغليف: بطاقة ورقية + تغليف حراري (شرينك).",
    "cat": "مماسح مسطحة",
    "img": "product_images/image119.png",
    "price": 107,
    "oldPrice": 145,
    "badge": "",
    "stars": 4.5,
    "reviews": 295,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 116,
    "code": "GSG007",
    "name": "مناديل من النسيج غير المنسوج 3 قطع",
    "name_en": "Non-Woven Cloths 3pcs",
    "desc": "قطع من النسيج غير المنسوج، المقاس: 38×40 سم، الخامة: 50% فسكوز و50% بوليستر، تغليف بكيس شفاف 3 قطع/كيس، الوزن 120 جم/م²، بثلاثة ألوان مختلطة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image207.jpeg",
    "price": 13,
    "oldPrice": 18,
    "badge": "",
    "stars": 4.6,
    "reviews": 58,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 117,
    "code": "GSG009",
    "name": "مناديل من النسيج غير المنسوج 10 قطع",
    "name_en": "Non-Woven Cloths 10pcs",
    "desc": "قطع من النسيج غير المنسوج، المقاس: 31×35 سم، الوزن 100 جم/م²، الخامة: 50% فسكوز و50% بوليستر، 10 قطع/كيس، بخمسة ألوان مختلطة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image208.jpeg",
    "price": 23,
    "oldPrice": 31,
    "badge": "",
    "stars": 4.7,
    "reviews": 71,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 118,
    "code": "GSG010",
    "name": "إسفنجة سليلوز 5 قطع",
    "name_en": "Cellulose Sponge 5pcs",
    "desc": "المقاس: 18×20 سم، 5 قطع/عبوة، كيس PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image159.jpeg",
    "price": 23,
    "oldPrice": 31,
    "badge": "",
    "stars": 4.8,
    "reviews": 84,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 119,
    "code": "GSG028",
    "name": "إسفنجة سليلوز 3 قطع",
    "name_en": "Cellulose Sponge 3pcs",
    "desc": "المقاس: 18×20 سم، 3 قطع/عبوة، كيس PP.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image143.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.9,
    "reviews": 97,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 120,
    "code": "GSG030",
    "name": "سجادة تجفيف",
    "name_en": "Drying Mat",
    "desc": "سجادة تجفيف مقاس 38×51 سم، وزن 87 جم، قماش منقوش من الوجهين، حشوة إسفنجية، بلونين مختلطين، 12 قطعة/كيس داخلي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image186.jpeg",
    "price": 30,
    "oldPrice": 41,
    "badge": "",
    "stars": 4.5,
    "reviews": 110,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 121,
    "code": "GSG015",
    "name": "مناديل من الألياف الدقيقة 10 قطع",
    "name_en": "Microfiber Cloths 10PCS",
    "desc": "مناديل قماشية من الألياف الدقيقة (70% بوليستر و30% بولي أميد)، لون أزرق، المقاس: 35×35 سم، 10 قطع/كيس، الوزن 400 جم/م² (50 جم/قطعة)، 24 كيساً/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image37.jpeg",
    "price": 98,
    "oldPrice": 133,
    "badge": "",
    "stars": 4.6,
    "reviews": 123,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 122,
    "code": "GSG016",
    "name": "مناديل من الألياف الدقيقة",
    "name_en": "MICROFIBER CLOTHS",
    "desc": "مناديل قماشية من الألياف الدقيقة، 8 قطع، المقاس: 30×30 سم (80% بوليستر و20% بولي أميد)، وزن 20 جم/قطعة، بنفس اللون الموضح في الصورة، تغليف بعلبة ملونة، 48 قطعة/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image41.jpeg",
    "price": 55,
    "oldPrice": 74,
    "badge": "",
    "stars": 4.7,
    "reviews": 136,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 123,
    "code": "GSH001",
    "name": "إسفنجة جلي 6 قطع",
    "name_en": "Sponge Scourer 6pcs",
    "desc": "إسفنجة جلي مقاس 13×9 سم، 6 قطع/عبوة، بحبيبات كاشطة من الداخل.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image53.png",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.8,
    "reviews": 149,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 124,
    "code": "GSH003",
    "name": "إسفنجة جلي",
    "name_en": "Sponge Scourer",
    "desc": "المقاس: 9×5.8×3 سم/قطعة، 10 قطع/كيس.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image54.png",
    "price": 21,
    "oldPrice": 29,
    "badge": "",
    "stars": 4.9,
    "reviews": 162,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 125,
    "code": "GSH004",
    "name": "قفازات لاتكس",
    "name_en": "Latex Gloves",
    "desc": "زوجان لكل كيس شفاف، مقاس كبير (L)، وزن 37 جم × زوجان، لون أصفر.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image102.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.5,
    "reviews": 175,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 126,
    "code": "GSH031",
    "name": "طقم إسفنج جلي",
    "name_en": "Scrub sponge Set",
    "desc": "إسفنجة مقاس 9.5×7×4 سم، إسفنجة جلي مقاس 12×9×0.7 سم (بحبيبات كاشطة من الداخل)، 6 قطع إسفنج + 4 قطع إسفنجة جلي = 10 قطع، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image200.jpeg",
    "price": 26,
    "oldPrice": 36,
    "badge": "",
    "stars": 4.6,
    "reviews": 188,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 127,
    "code": "GSH032",
    "name": "إسفنجة جلي 5 قطع",
    "name_en": "Sponge Scourer 5pcs",
    "desc": "المقاس: 11×6×3.5 سم/قطعة، 5 قطع/كيس.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image201.jpeg",
    "price": 12,
    "oldPrice": 16,
    "badge": "",
    "stars": 4.7,
    "reviews": 201,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 128,
    "code": "GSH033",
    "name": "إسفنجة جلي 5 قطع",
    "name_en": "Sponge Scourer 5pcs",
    "desc": "المقاس: 12.5×6.5×3 سم/قطعة، 24 قطعة/كيس.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image180.jpeg",
    "price": 86,
    "oldPrice": 116,
    "badge": "",
    "stars": 4.8,
    "reviews": 214,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 129,
    "code": "GSH034",
    "name": "طقم إسفنجة جلي ومنشفة",
    "name_en": "Scouring pad&Towel set",
    "desc": "طقم إسفنجة جلي ومنشفة: 1) إسفنجة مقاس 17×10×4 سم، 2) إسفنجة جلي مقاس 17×8×4 سم، 3) قطعة قماش شمواه مقاس 35.5×35.5 سم، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image197.jpeg",
    "price": 32,
    "oldPrice": 43,
    "badge": "",
    "stars": 4.9,
    "reviews": 227,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 130,
    "code": "GSH035",
    "name": "إسفنجة جلي شبكية",
    "name_en": "Mesh scouring pad",
    "desc": "إسفنجة جلي شبكية (إسفنج PU) مقاس 11×5×0.5 سم، 30 قطعة/كيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image198.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.5,
    "reviews": 240,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 131,
    "code": "GSH036",
    "name": "إسفنجة جلي",
    "name_en": "Scouring pad",
    "desc": "إسفنجة جلي مقاس 11×5×0.5 سم، 30 قطعة/كيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image199.jpeg",
    "price": 22,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.6,
    "reviews": 253,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 132,
    "code": "GSH006",
    "name": "قفازات نيتريل للاستعمال مرة واحدة",
    "name_en": "Disposable Nitrile Gloves",
    "desc": "قفازات نيتريل للاستعمال مرة واحدة، مقاس كبير (L)، 50 قطعة/علبة ملونة (25 زوجاً)، لون أبيض.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image3.jpeg",
    "price": 69,
    "oldPrice": 93,
    "badge": "",
    "stars": 4.7,
    "reviews": 266,
    "color": "white",
    "inStock": true
  },
  {
    "id": 133,
    "code": "GSH026",
    "name": "قفازات نيتريل للاستعمال مرة واحدة (مقاس كبير)",
    "name_en": "Disposable Nitrile Gloves L",
    "desc": "قفازات نيتريل للاستعمال مرة واحدة، مقاس كبير (L)، 50 قطعة/كيس ملون (25 زوجاً)، لون أزرق، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image147.jpeg",
    "price": 62,
    "oldPrice": 83,
    "badge": "",
    "stars": 4.8,
    "reviews": 279,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 134,
    "code": "GSH029",
    "name": "قفاز PVC للاستعمال مرة واحدة (مقاس كبير)",
    "name_en": "PVC Disposable glove.L",
    "desc": "قفازات PVC للاستعمال مرة واحدة، مقاس كبير (L)، 50 قطعة/كيس ملون (25 زوجاً)، لون أبيض، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image148.jpeg",
    "price": 37,
    "oldPrice": 50,
    "badge": "",
    "stars": 4.9,
    "reviews": 292,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 135,
    "code": "GSH019",
    "name": "قفازات منزلية",
    "name_en": "HOUSEHOLD GLOVES",
    "desc": "قفازات منزلية من خامة اللاتكس، زوج واحد/كيس، الوزن 60 جم/زوج، المقاس: كبير 30×10 سم، بلونين أزرق وأصفر مطابقين للصورة، 12 كيساً/كيس داخلي، 10 أكياس داخلية/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image94.jpeg",
    "price": 14,
    "oldPrice": 19,
    "badge": "",
    "stars": 4.5,
    "reviews": 55,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 136,
    "code": "GSH007",
    "name": "إسفنجة فولاذية جلي 2 قطعة",
    "name_en": "Stainless Steel Scourer 2pcs",
    "desc": "فولاذ مقاوم للصدأ، قطعتان × 15 جم/كيس شفاف.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image55.png",
    "price": 6,
    "oldPrice": 7,
    "badge": "",
    "stars": 4.6,
    "reviews": 68,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 137,
    "code": "GSH008",
    "name": "إسفنجة فولاذية جلي 4 قطع",
    "name_en": "Stainless Steel Scourer 4pcs",
    "desc": "فولاذ مقاوم للصدأ، 4 قطع × 15 جم/كيس شفاف.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image56.png",
    "price": 9,
    "oldPrice": 13,
    "badge": "",
    "stars": 4.7,
    "reviews": 81,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 138,
    "code": "GSH009",
    "name": "إسفنجة فولاذية جلي 6 قطع",
    "name_en": "Stainless Steel Scourer  6PCS",
    "desc": "فولاذ مقاوم للصدأ، 6 قطع × 15 جم/كيس شفاف.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image57.png",
    "price": 13,
    "oldPrice": 18,
    "badge": "",
    "stars": 4.8,
    "reviews": 94,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 139,
    "code": "GSH010",
    "name": "إسفنجة فولاذية جلي 12 قطعة",
    "name_en": "Stainless Steel Scourer  12PCS",
    "desc": "فولاذ مقاوم للصدأ، 12 قطعة × 15 جم، قطعة واحدة/كيس شفاف، تغليف 12 قطعة ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image58.png",
    "price": 35,
    "oldPrice": 47,
    "badge": "",
    "stars": 4.9,
    "reviews": 107,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 140,
    "code": "GSH012",
    "name": "إسفنجة جلي",
    "name_en": "Sponge Scouring Pad",
    "desc": "إسفنجة جلي مقاس 9.3×7×4.2 سم، بحبيبات كاشطة من الداخل، 3 قطع/عبوة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image103.jpeg",
    "price": 12,
    "oldPrice": 16,
    "badge": "",
    "stars": 4.5,
    "reviews": 120,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 141,
    "code": "GSH022",
    "name": "إسفنجة سليلوز مع إسفنجة جلي",
    "name_en": "CELLULOSE SPONGE SCOURING PAD",
    "desc": "إسفنجة سليلوز مع إسفنجة جلي، ألوان مختلطة، المقاس: 11.2×6.8×2 سم، 6 قطع/عبوة، 12 عبوة/كيس داخلي، 4 أكياس داخلية/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image140.jpeg",
    "price": 32,
    "oldPrice": 43,
    "badge": "",
    "stars": 4.6,
    "reviews": 133,
    "color": "as picture",
    "inStock": true
  },
  {
    "id": 142,
    "code": "GSH023",
    "name": "إسفنجة سليلوز مع إسفنجة جلي",
    "name_en": "CELLULOSE SPONGE SCOURING PAD",
    "desc": "إسفنجة سليلوز مع إسفنجة جلي، ألوان مختلطة، المقاس: 11.2×6.8×2 سم، 9 قطع/عبوة، 6 عبوات/كيس داخلي، 8 أكياس داخلية/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image141.jpeg",
    "price": 48,
    "oldPrice": 65,
    "badge": "",
    "stars": 4.7,
    "reviews": 146,
    "color": "as picture",
    "inStock": true
  },
  {
    "id": 143,
    "code": "GSF003",
    "name": "إسفنجة جلي",
    "name_en": "SPONGE SCOURER",
    "desc": "إسفنجة جلي مقاس 12.5×9×1.7 سم، 3 قطع/عبوة، 12 عبوة/كيس داخلي، 96 قطعة/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image38.jpeg",
    "price": 10,
    "oldPrice": 13,
    "badge": "",
    "stars": 4.8,
    "reviews": 159,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 144,
    "code": "GSF004",
    "name": "إسفنجة جلي",
    "name_en": "SPONGE SCOURER",
    "desc": "إسفنجة جلي مقاس 10.5×9×1.8 سم، 3 قطع/عبوة، 12 عبوة/كيس داخلي، 96 قطعة/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image39.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.9,
    "reviews": 172,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 145,
    "code": "GSF005",
    "name": "إسفنجة جلي",
    "name_en": "SPONGE SCOURER",
    "desc": "إسفنجة جلي مقاس 16×9×1.5 سم، 3 قطع/عبوة، 12 عبوة/كيس داخلي، 96 قطعة/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image87.png",
    "price": 19,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.5,
    "reviews": 185,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 146,
    "code": "GSF002",
    "name": "إسفنجة جلي",
    "name_en": "Sponge Scourer",
    "desc": "إسفنجة جلي مقاس 13×9×1.7 سم، 12 قطعة/طقم، كل قطعة معبأة في كيس شفاف منفصل.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image169.jpeg",
    "price": 49,
    "oldPrice": 66,
    "badge": "",
    "stars": 4.6,
    "reviews": 198,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 147,
    "code": "KH2402",
    "name": "فرشاة تنظيف الأحواض والبلاط",
    "name_en": "Tub&Tile Scrubber",
    "desc": "فرشاة جلي مقاس 14×8 سم، مع إسفنجة جلي مقاس 15×9×2 سم، قطعة واحدة، لون رمادي، حامل فرشاة بلاستيكي أزرق، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image169.jpeg",
    "price": 18,
    "oldPrice": 24,
    "badge": "",
    "stars": 4.7,
    "reviews": 211,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 148,
    "code": "KH2506",
    "name": "فرشاة تنظيف الأحواض والبلاط",
    "name_en": "Tub&Tile Scrubber",
    "desc": "مقبض بلاستيكي طول 41 سم، إسفنجة جلي مقاس 15×9.5×2 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image164.jpeg",
    "price": 21,
    "oldPrice": 28,
    "badge": "",
    "stars": 4.8,
    "reviews": 224,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 149,
    "code": "GSW001",
    "name": "إسفنجة",
    "name_en": "Sponge",
    "desc": "إسفنجة PU مقاس 21.5×11×5.7 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image65.png",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.9,
    "reviews": 237,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 150,
    "code": "GSW003",
    "name": "إسفنجة من الألياف الدقيقة",
    "name_en": "Microfiber Sponge",
    "desc": "إسفنجة بيضاوية الشكل مقاس 23×12×5 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image5.jpeg",
    "price": 21,
    "oldPrice": 29,
    "badge": "",
    "stars": 4.5,
    "reviews": 250,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 151,
    "code": "GSW005",
    "name": "قفاز شينيل",
    "name_en": "Chenille Glove",
    "desc": "المقاس: 24×16 سم، قفاز من الألياف الدقيقة، قابل للاستخدام من الوجهين.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image6.jpeg",
    "price": 29,
    "oldPrice": 39,
    "badge": "",
    "stars": 4.6,
    "reviews": 263,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 152,
    "code": "GSW007",
    "name": "منشفة فاخرة من الألياف الدقيقة",
    "name_en": "Microfibre Luxury Towel",
    "desc": "منشفة من الألياف الدقيقة مقاس 45×38 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image7.jpeg",
    "price": 37,
    "oldPrice": 50,
    "badge": "",
    "stars": 4.7,
    "reviews": 276,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 153,
    "code": "GSW008",
    "name": "قطعة قماش للمسح",
    "name_en": "Wiping cloth",
    "desc": "منشفة من الألياف الدقيقة مقاس 40×40 سم؛ 4 قطع/عبوة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image8.jpeg",
    "price": 32,
    "oldPrice": 44,
    "badge": "",
    "stars": 4.8,
    "reviews": 289,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 154,
    "code": "GSW010",
    "name": "منفضة شينيل",
    "name_en": "Chenille Duster",
    "desc": "منفضة شينيل مقاس 56×6 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image66.png",
    "price": 37,
    "oldPrice": 50,
    "badge": "",
    "stars": 4.9,
    "reviews": 52,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 155,
    "code": "KF2202",
    "name": "منفضة شينيل",
    "name_en": "Chenille Duster",
    "desc": "منفضة من الألياف الدقيقة، الطول الإجمالي: 57 سم، خامة الرأس البديل: شينيل + قماش ألياف دقيقة مقاس 44×7 سم، مقبض بلاستيكي يحمل شعار Kleaner، مقبض معدني قابل للتطويل من 70 إلى 120 سم، تغليف ببطاقة ورقية.",
    "cat": "قطع غيار",
    "img": "product_images/image196.jpeg",
    "price": 57,
    "oldPrice": 76,
    "badge": "",
    "stars": 4.5,
    "reviews": 65,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 156,
    "code": "GSK003",
    "name": "مكنسة خارجية",
    "name_en": "Outdoor broom",
    "desc": "الجزء البلاستيكي مقاس 27×11.8 سم، طول الشعيرات 10 سم، مقبض معدني 118 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image177.jpeg",
    "price": 44,
    "oldPrice": 59,
    "badge": "",
    "stars": 4.6,
    "reviews": 78,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 157,
    "code": "GSK004",
    "name": "مكنسة خارجية",
    "name_en": "Outdoor broom",
    "desc": "الجزء البلاستيكي مقاس 22.5×17.5 سم، طول الشعيرات 15 سم، مقبض معدني 120 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image59.png",
    "price": 52,
    "oldPrice": 71,
    "badge": "",
    "stars": 4.7,
    "reviews": 91,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 158,
    "code": "GSK006",
    "name": "مكنسة",
    "name_en": "Broom",
    "desc": "رأس مكنسة 27 سم ببرغي إيطالي، طول الشعيرات 9 سم، مقبض معدني 130 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image61.png",
    "price": 47,
    "oldPrice": 63,
    "badge": "",
    "stars": 4.8,
    "reviews": 104,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 159,
    "code": "K20001",
    "name": "مكنسة مضادة للغبار",
    "name_en": "Anti-Dust Broom",
    "desc": "رأس مكنسة 25 سم ببرغي إيطالي، طول الشعيرات 9 سم، بتصميم 2 في 1 مضاد للغبار لتحسين امتصاص الغبار، مقبض معدني 120 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image73.png",
    "price": 48,
    "oldPrice": 65,
    "badge": "",
    "stars": 4.9,
    "reviews": 117,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 160,
    "code": "K20002",
    "name": "مكنسة مضادة للغبار",
    "name_en": "Anti-Dust Broom",
    "desc": "رأس مكنسة 27 سم من مادة PP ببرغي إيطالي، طول الشعيرات 11 سم، مقبض معدني 130 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image74.png",
    "price": 51,
    "oldPrice": 69,
    "badge": "",
    "stars": 4.5,
    "reviews": 130,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 161,
    "code": "K20003",
    "name": "مكنسة مضادة للغبار",
    "name_en": "Anti-Dust Broom",
    "desc": "رأس مكنسة 31 سم ببرغي إيطالي، طول الشعيرات 10 سم، مقبض معدني 130 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image14.jpeg",
    "price": 58,
    "oldPrice": 78,
    "badge": "",
    "stars": 4.6,
    "reviews": 143,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 162,
    "code": "KK2304",
    "name": "مكنسة",
    "name_en": "Broom",
    "desc": "مقبض معدني 130 سم ببرغي إيطالي، عرض رأس المكنسة: 33 سم، طول الشعيرات 10.5 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image82.png",
    "price": 56,
    "oldPrice": 76,
    "badge": "",
    "stars": 4.7,
    "reviews": 156,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 163,
    "code": "KK2002",
    "name": "فرشاة أرضية",
    "name_en": "floor brush",
    "desc": "فرشاة أرضية مقاس 26×7.5 سم، شعيرات رمادية طول 4 سم، حافة TPR مقاس 1 سم، مقبض معدني برأس حلزوني إيطالي، الطول الإجمالي: 120 سم بقطر 21.5 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image81.png",
    "price": 50,
    "oldPrice": 67,
    "badge": "",
    "stars": 4.8,
    "reviews": 169,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 164,
    "code": "K19004",
    "name": "منظف متعدد الاستخدامات",
    "name_en": "Multi-Purpose Cleaner",
    "desc": "فرشاة بلاستيكية ببرغي إيطالي، المقاس: 23×17×5 سم، شعيرات PP طول 30 مم، مقبض معدني قابل للتطويل من 70 إلى 120 سم بقطر 19/21.5 مم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image68.png",
    "price": 58,
    "oldPrice": 78,
    "badge": "",
    "stars": 4.9,
    "reviews": 182,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 165,
    "code": "GSK017",
    "name": "فرشاة أرضية",
    "name_en": "FLOOR BRUSH",
    "desc": "رأس ممسحة أرضية (سكوتش) 35 سم ببرغي إيطالي، المقاس: 35×6×6 سم، شعيرات TPR طول 3.5 سم، مقبض معدني 130 سم، تغليف ببطاقة ورقية، 24 قطعة/كرتون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image99.jpeg",
    "price": 64,
    "oldPrice": 86,
    "badge": "",
    "stars": 4.5,
    "reviews": 195,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 166,
    "code": "KK2308",
    "name": "ممسحة أرضية (سكوتش)",
    "name_en": "FLOOR SQUEEGEE",
    "desc": "ممسحة أرضية (سكوتش)، مقبض معدني 120 سم برأس حلزوني إيطالي، رأس سكوتش TPR مقاس 40 سم، تغليف ببطاقة ورقية.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image83.png",
    "price": 35,
    "oldPrice": 48,
    "badge": "",
    "stars": 4.6,
    "reviews": 208,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 167,
    "code": "GSK005",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 42 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم وبرغي إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image60.png",
    "price": 48,
    "oldPrice": 65,
    "badge": "",
    "stars": 4.7,
    "reviews": 221,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 168,
    "code": "GSK008",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 33 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم وبرغي إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image62.png",
    "price": 43,
    "oldPrice": 58,
    "badge": "",
    "stars": 4.8,
    "reviews": 234,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 169,
    "code": "GSK009",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 53 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم وبرغي إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image63.png",
    "price": 52,
    "oldPrice": 71,
    "badge": "",
    "stars": 4.9,
    "reviews": 247,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 170,
    "code": "KK2416",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 33 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم برأس حلزوني إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image121.jpeg",
    "price": 43,
    "oldPrice": 58,
    "badge": "",
    "stars": 4.5,
    "reviews": 260,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 171,
    "code": "KK2417",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 43 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم برأس حلزوني إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image122.jpeg",
    "price": 47,
    "oldPrice": 64,
    "badge": "",
    "stars": 4.6,
    "reviews": 273,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 172,
    "code": "KK2418",
    "name": "ممسحة أرضية",
    "name_en": "Floor squeegee",
    "desc": "رأس بلاستيكي 53 سم مع مسّاحة EVA، رأس بتصميم مشبك، مقبض معدني 120 سم بقطر 21.5 مم برأس حلزوني إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image123.jpeg",
    "price": 51,
    "oldPrice": 69,
    "badge": "",
    "stars": 4.7,
    "reviews": 286,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 173,
    "code": "KK2623",
    "name": "ممسحة أرضية 16.5 إنش",
    "name_en": "16.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة TPR مقاس 16.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image187.jpeg",
    "price": 42,
    "oldPrice": 56,
    "badge": "",
    "stars": 4.8,
    "reviews": 299,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 174,
    "code": "KK2624",
    "name": "ممسحة أرضية 12.5 إنش",
    "name_en": "12.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة EVA مقاس 12.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image188.jpeg",
    "price": 38,
    "oldPrice": 51,
    "badge": "",
    "stars": 4.9,
    "reviews": 62,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 175,
    "code": "KK2625",
    "name": "ممسحة أرضية 16.5 إنش",
    "name_en": "16.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة EVA مقاس 16.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image189.jpeg",
    "price": 41,
    "oldPrice": 55,
    "badge": "",
    "stars": 4.5,
    "reviews": 75,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 176,
    "code": "KK2626",
    "name": "ممسحة أرضية 20.5 إنش",
    "name_en": "20.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة EVA مقاس 20.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image190.jpeg",
    "price": 45,
    "oldPrice": 60,
    "badge": "",
    "stars": 4.6,
    "reviews": 88,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 177,
    "code": "KK2627",
    "name": "ممسحة أرضية 16.5 إنش",
    "name_en": "16.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة EVA مقاس 16.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image191.jpeg",
    "price": 44,
    "oldPrice": 59,
    "badge": "",
    "stars": 4.7,
    "reviews": 101,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 178,
    "code": "KK2628",
    "name": "ممسحة أرضية 20.5 إنش",
    "name_en": "20.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، مسّاحة EVA مقاس 20.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image192.jpeg",
    "price": 48,
    "oldPrice": 65,
    "badge": "",
    "stars": 4.8,
    "reviews": 114,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 179,
    "code": "KK2629",
    "name": "ممسحة أرضية 16.5 إنش",
    "name_en": "16.5\" FLOOR SQUEEGEE",
    "desc": "مقبض معدني 120 سم، للاستخدام المزدوج مع رأس فرشاة، مسّاحة EVA مقاس 16.5 إنش.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image193.jpeg",
    "price": 43,
    "oldPrice": 58,
    "badge": "",
    "stars": 4.9,
    "reviews": 127,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 180,
    "code": "KK2630",
    "name": "ممسحة أرضية 16.5 إنش",
    "name_en": "Floor squeegee 16.5“",
    "desc": "رأس من الفولاذ المقاوم للصدأ والبلاستيك مقاس 16.5 إنش مع مسّاحة EVA، مقبض معدني 120 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image194.jpeg",
    "price": 52,
    "oldPrice": 71,
    "badge": "",
    "stars": 4.5,
    "reviews": 140,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 181,
    "code": "KK2631",
    "name": "ممسحة أرضية 20.5 إنش",
    "name_en": "Floor squeegee 20.5“",
    "desc": "رأس من الفولاذ المقاوم للصدأ والبلاستيك مقاس 20.5 إنش مع مسّاحة EVA، مقبض معدني 120 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image195.jpeg",
    "price": 57,
    "oldPrice": 76,
    "badge": "",
    "stars": 4.6,
    "reviews": 153,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 182,
    "code": "KK2520-H",
    "name": "رأس ممسحة أرضية EVA",
    "name_en": "EVA floor squeegee  head",
    "desc": "مسّاحة EVA مقاس 58 سم ببرغي إيطالي، تحمل شعار Kleaner.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image165.jpeg",
    "price": 60,
    "oldPrice": 82,
    "badge": "",
    "stars": 4.7,
    "reviews": 166,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 183,
    "code": "GSM002",
    "name": "مقبض معدني",
    "name_en": "Metal Handle",
    "desc": "مقبض معدني 130 سم بقطر 25 مم برأس حلزوني إيطالي.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image170.jpeg",
    "price": 20,
    "oldPrice": 27,
    "badge": "",
    "stars": 4.8,
    "reviews": 179,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 184,
    "code": "KT2412",
    "name": "دلو مع عصّارة",
    "name_en": "Bucket with Wringer",
    "desc": "دلو مع عصّارة سعة 15 لتراً، مقبض معدني، الوزن 770 جم، يحمل شعار Kleaner، المقاس: 39×28.5×27 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image93.jpeg",
    "price": 88,
    "oldPrice": 119,
    "badge": "",
    "stars": 4.9,
    "reviews": 192,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 185,
    "code": "GST002",
    "name": "ممسحة تورنيدو",
    "name_en": "Tornado Mop",
    "desc": "نظام دوران باتجاهين، مقبض من الفولاذ المقاوم للصدأ مكوّن من قسمين طول 118 سم، مقاس المنتج: 46×27×23 سم، سلة من الفولاذ المقاوم للصدأ، تصميم بعجلات متحركة، السعة 8 لترات، مع رأسين ممسحة بديلين بالداخل.",
    "cat": "قطع غيار",
    "img": "product_images/image125.jpeg",
    "price": 305,
    "oldPrice": 412,
    "badge": "",
    "stars": 4.5,
    "reviews": 205,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 186,
    "code": "KT2210",
    "name": "ممسحة تورنيدو",
    "name_en": "Tornado Mop",
    "desc": "نظام دوران باتجاهين، مقبض من الفولاذ المقاوم للصدأ مكوّن من قسمين طول 123 سم، سلة بلاستيكية، مقاس المنتج: 47.7×25.7×45.3 سم، فتحة صب لتسهيل التصريف، السعة 8 لترات، مع رأسين ممسحة بديلين من الألياف الدقيقة، تغليف بعلبة ملونة.",
    "cat": "قطع غيار",
    "img": "product_images/image126.jpeg",
    "price": 234,
    "oldPrice": 316,
    "badge": "",
    "stars": 4.6,
    "reviews": 218,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 187,
    "code": "KT2211",
    "name": "ممسحة تورنيدو",
    "name_en": "Tornado Mop",
    "desc": "نظام دوران باتجاهين، مقبض من الفولاذ المقاوم للصدأ مكوّن من قسمين طول 123 سم، سلة من الفولاذ المقاوم للصدأ، مقاس المنتج: 47.7×25.7×45.3 سم، فتحة صب لتسهيل التصريف، السعة 8 لترات، مع رأسين ممسحة بديلين من الألياف الدقيقة، تغليف بعلبة ملونة.",
    "cat": "قطع غيار",
    "img": "product_images/image127.jpeg",
    "price": 267,
    "oldPrice": 361,
    "badge": "",
    "stars": 4.7,
    "reviews": 231,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 188,
    "code": "KT2414",
    "name": "ممسحة تورنيدو",
    "name_en": "Tornado Mop",
    "desc": "نظام دوران باتجاهين، مقبض من الفولاذ المقاوم للصدأ مكوّن من قسمين طول 123 سم، سلة من الفولاذ المقاوم للصدأ، مقاس المنتج: 47×28×25.5 سم، السعة 8 لترات، مع رأسين ممسحة بديلين من الألياف الدقيقة، تغليف بعلبة ملونة.",
    "cat": "قطع غيار",
    "img": "product_images/image128.jpeg",
    "price": 279,
    "oldPrice": 377,
    "badge": "",
    "stars": 4.8,
    "reviews": 244,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 189,
    "code": "KT2416",
    "name": "ممسحة تورنيدو",
    "name_en": "Tornado Mop",
    "desc": "مقبض من الفولاذ المقاوم للصدأ مكوّن من قسمين طول 123 سم، فتحة صب لتسهيل التصريف، سلة من الفولاذ المقاوم للصدأ، مقاس الدلو: 49×29×27 سم، نظام دوران ثلاثي الاتجاهات، عصر بدون استخدام اليدين عبر دواسة قدم، مع رأسين ممسحة بديلين، تغليف بعلبة ملونة.",
    "cat": "قطع غيار",
    "img": "product_images/image129.jpeg",
    "price": 380,
    "oldPrice": 512,
    "badge": "",
    "stars": 4.9,
    "reviews": 257,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 190,
    "code": "GSR-T002-1",
    "name": "رأس ممسحة بديل",
    "name_en": "Mop Refill",
    "desc": "الوزن 124 جم، حلقة بلاستيكية قطر 15.7 سم، خيوط من الألياف الدقيقة بألوان متعددة، تغليف بكيس PP.",
    "cat": "قطع غيار",
    "img": "product_images/image30.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.5,
    "reviews": 270,
    "color": "white",
    "inStock": true
  },
  {
    "id": 191,
    "code": "GST003",
    "name": "ممسحة مسطحة مع دلو ونظام كشط",
    "name_en": "Scraping Flat   Bucket Mop",
    "desc": "طقم دلو وممسحة مسطحة بنظام الكشط، مقاس الدلو: 38×18×18 سم، إطار الممسحة: 31.5×12 سم، مقبض من الفولاذ المقاوم للصدأ رباعي الأقسام طوله 118 سم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image4.jpeg",
    "price": 229,
    "oldPrice": 310,
    "badge": "",
    "stars": 4.6,
    "reviews": 283,
    "color": "Blue",
    "inStock": true
  },
  {
    "id": 192,
    "code": "GSR-T003",
    "name": "رأس ممسحة بديل من الألياف الدقيقة",
    "name_en": "Microfiber Mop Refill",
    "desc": "رأس بديل من الألياف الدقيقة للموديل GST003، المقاس: 32×12 سم.",
    "cat": "قطع غيار",
    "img": "product_images/image90.png",
    "price": 18,
    "oldPrice": 24,
    "badge": "",
    "stars": 4.7,
    "reviews": 296,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 193,
    "code": "GSZ004",
    "name": "حامل ممسحة ومكنسة",
    "name_en": "Mop & Broom holder",
    "desc": "المقاس: 43×6.2×8.5 سم، حامل بلاستيكي بخمسة أوضاع، 6 عناصر تعليق، تغليف كل طقم بعلبة ملونة، مع 4 براغي داخل كل طقم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image12.jpeg",
    "price": 95,
    "oldPrice": 128,
    "badge": "",
    "stars": 4.8,
    "reviews": 59,
    "color": "grey",
    "inStock": true
  },
  {
    "id": 194,
    "code": "KZ2102",
    "name": "حامل ممسحة ومكنسة",
    "name_en": "Mop & Broom holder",
    "desc": "مقاس كل قطعة: 26.8×4.1×3.9 سم، حامل بلاستيكي بثلاثة أوضاع، خطافات حائط بلاصق قوي، تغليف كل طقم بعلبة بلاستيكية شفافة، السعة التحميلية: حوالي 3 كجم.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image20.png",
    "price": 26,
    "oldPrice": 36,
    "badge": "",
    "stars": 4.9,
    "reviews": 72,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 195,
    "code": "GSL008",
    "name": "بكرة إزالة الوبر",
    "name_en": "Lint Roller",
    "desc": "الطول: 23 سم، 60 ورقة/لفافة × 10 سم، الوزن 40 جم/م².",
    "cat": "مماسح مسطحة",
    "img": "product_images/image22.png",
    "price": 22,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.5,
    "reviews": 85,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 196,
    "code": "GSL010",
    "name": "بكرة إزالة الوبر",
    "name_en": "Lint Roller",
    "desc": "الطول: 23 سم، 60 ورقة/لفافة، 3 لفافات/عبوة، الوزن 40 جم/م².",
    "cat": "مماسح مسطحة",
    "img": "product_images/image23.png",
    "price": 55,
    "oldPrice": 74,
    "badge": "",
    "stars": 4.6,
    "reviews": 98,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 197,
    "code": "GSL011",
    "name": "بكرة إزالة الوبر",
    "name_en": "Lint Roller",
    "desc": "بكرة إزالة الوبر بغطاء بلاستيكي مقاس 17.5×23 سم، 60 ورقة/لفافة مقاس 16 سم بقطر 4.3 سم، الوزن 38 جم/م².",
    "cat": "مماسح مسطحة",
    "img": "product_images/image120.jpeg",
    "price": 47,
    "oldPrice": 63,
    "badge": "",
    "stars": 4.7,
    "reviews": 111,
    "color": "blue",
    "inStock": true
  },
  {
    "id": 198,
    "code": "GSL013",
    "name": "كيس قمامة صغير 40 قطعة 7.5 لتر",
    "name_en": "Garbage bag-S 40PCS  7.5L",
    "desc": "كيس قمامة صغير سعة 7.5 لتر، الخامة: HDPE+LLDPE، لون أسود، المقاس: 40×45 سم، 40 قطعة/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image150.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.8,
    "reviews": 124,
    "color": "black",
    "inStock": true
  },
  {
    "id": 199,
    "code": "GSL015",
    "name": "كيس قمامة كبير 30 قطعة 15 لتر",
    "name_en": "Garbage bag-L 30PCS  15L",
    "desc": "كيس قمامة كبير سعة 15 لتراً، الخامة: HDPE+LLDPE، لون أسود، المقاس: 50×60 سم، 30 قطعة/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image151.jpeg",
    "price": 19,
    "oldPrice": 26,
    "badge": "",
    "stars": 4.9,
    "reviews": 137,
    "color": "black",
    "inStock": true
  },
  {
    "id": 200,
    "code": "GSL017",
    "name": "أكياس قمامة بتصميم الصدرية 30 قطعة/15 لتر",
    "name_en": "VEST-TYPE GARBAGE BAGS 30PCS/15L",
    "desc": "أكياس قمامة بتصميم الصدرية سعة 15 لتراً، الخامة: HDPE+LLDPE، لون أسود، المقاس: 50×70 سم، 30 قطعة/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image152.jpeg",
    "price": 23,
    "oldPrice": 30,
    "badge": "",
    "stars": 4.5,
    "reviews": 150,
    "color": "black",
    "inStock": true
  },
  {
    "id": 201,
    "code": "GSL019",
    "name": "أكياس قمامة بحبل سحب 30 قطعة/10 لتر",
    "name_en": "DRAWSTRING GARBAGE BAGS 30PCS/10L",
    "desc": "أكياس قمامة بحبل سحب سعة 10 لترات، الخامة: HDPE+LLDPE، لون أسود، المقاس: 45×50 سم، 30 قطعة/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image153.jpeg",
    "price": 16,
    "oldPrice": 22,
    "badge": "",
    "stars": 4.6,
    "reviews": 163,
    "color": "black",
    "inStock": true
  },
  {
    "id": 202,
    "code": "GSL021",
    "name": "كيس قمامة عالي التحمل 50 لتر",
    "name_en": "Heavy-Duty garbage bag 50L",
    "desc": "كيس قمامة عالي التحمل سعة 50 لتراً، الخامة: HDPE+LLDPE، لون أسود، المقاس: 63×80 سم، الوزن 95 جم، 10 قطع/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image154.jpeg",
    "price": 13,
    "oldPrice": 17,
    "badge": "",
    "stars": 4.7,
    "reviews": 176,
    "color": "black",
    "inStock": true
  },
  {
    "id": 203,
    "code": "GSL022",
    "name": "كيس قمامة عالي التحمل 100 لتر",
    "name_en": "Heavy-Duty garbage bag 100L",
    "desc": "كيس قمامة عالي التحمل سعة 100 لتر، الخامة: HDPE+LLDPE، لون أسود، المقاس: 75×105 سم، الوزن 153 جم، 10 قطع/لفافة، السماكة 1S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image155.jpeg",
    "price": 18,
    "oldPrice": 25,
    "badge": "",
    "stars": 4.8,
    "reviews": 189,
    "color": "black",
    "inStock": true
  },
  {
    "id": 204,
    "code": "GSL023",
    "name": "كيس قمامة عالي التحمل 120 لتر",
    "name_en": "Heavy-Duty garbage bag 120L",
    "desc": "كيس قمامة عالي التحمل سعة 120 لتراً، الخامة: HDPE+LLDPE، لون أسود، المقاس: 100×120 سم، الوزن 335 جم، 10 قطع/لفافة، السماكة 1.5S، تغليف بكيس ملون.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image156.jpeg",
    "price": 39,
    "oldPrice": 53,
    "badge": "",
    "stars": 4.9,
    "reviews": 202,
    "color": "black",
    "inStock": true
  },
  {
    "id": 205,
    "code": "GST011",
    "name": "سلة مهملات 10 لتر",
    "name_en": "Dustbin 10L",
    "desc": "سلة مهملات بلاستيكية سعة 10 لتر، المقاس: 23×30 سم، مع ملصق.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image16.jpeg",
    "price": 56,
    "oldPrice": 76,
    "badge": "",
    "stars": 4.5,
    "reviews": 215,
    "color": "the same as photo",
    "inStock": true
  },
  {
    "id": 206,
    "code": "GST012",
    "name": "سلة مهملات 12 لتر",
    "name_en": "Dustbin 12L",
    "desc": "سلة مهملات بلاستيكية سعة 12 لتراً، المقاس: 30×33 سم، مع ملصق، بنظام الدواسة.",
    "cat": "مماسح مسطحة",
    "img": "product_images/image64.png",
    "price": 112,
    "oldPrice": 151,
    "badge": "",
    "stars": 4.6,
    "reviews": 228,
    "color": "the same as photo",
    "inStock": true
  }
];
